### ISSUE TITLE
オシャレってなんでしょうね？

### ISSUE THREAD

**Issue by Sota-Watanabe** [cdlab-sit/100knock#23]
Code Author: @higurashi-takuto 
Knock Number:02
https://github.com/cdlab-sit/100knock/blob/975817f70b3fb028406f6acd03f6bf47b0fac068/higurashi-takuto/02.py#L6-L10

オシャレ(?)にしてみましたがどうでしょうか
https://github.com/cdlab-sit/100knock/blob/975817f70b3fb028406f6acd03f6bf47b0fac068/Sota222/02.py#L6-L7

**Comment by higurashi-takuto** [comment]
これだったらわざわざ、lambda別にしないで、1ライナーの方がオシャレじゃない？

**Comment by Sota-Watanabe** [comment]
その通りでございます!!!
