### ISSUE TITLE
コーディング規約に反しています。

### ISSUE THREAD

**Issue by higurashi-takuto** [cdlab-sit/100knock#4]
https://github.com/cdlab-sit/100knock/blob/99fc16736788c383e7badf6d21a751099ba3a44e/kumbikumbiSIC/00.py#L1
コーディング規約では、演算子の前後にスペースが必要なので、`msg = "stressed"`が正しいと思います。

**Comment by Hikaru-Morita** [comment]
ありがとうございます。
